let data =  [
  {
    "id": "1",
    "title": "Spider-Man: Into the Spider-Verse",
    "image": "https://i.imgur.com/1Z1Z1Z1.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12345/spider-man_into_the_spider-verse",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Brian Michael Bendis",
    "publish_year": 2018
  },
  {
    "id": "2",
    "title": "Avengers: Endgame",
    "image": "https://i.imgur.com/2Z2Z2Z2.jpg",
    "price": 24.99,
    "url": "https://www.marvel.com/comics/issue/12346/avengers_endgame",
    "character_name": "Avengers",
    "category": "Superhero",
    "author": "Jim Starlin",
    "publish_year": 2019
  },
  {
    "id": "3",
    "title": "X-Men: Dark Phoenix",
    "image": "https://i.imgur.com/3Z3Z3Z3.jpg",
    "price": 15.99,
    "url": "https://www.marvel.com/comics/issue/12347/x-men_dark_phoenix",
    "character_name": "X-Men",
    "category": "Superhero",
    "author": "Chris Claremont",
    "publish_year": 1980
  },
  {
    "id": "4",
    "title": "Black Panther: A Nation Under Our Feet",
    "image": "https://i.imgur.com/4Z4Z4Z4.jpg",
    "price": 22.99,
    "url": "https://www.marvel.com/comics/issue/12348/black_panther_a_nation_under_our_feet",
    "character_name": "Black Panther",
    "category": "Superhero",
    "author": "Ta-Nehisi Coates",
    "publish_year": 2016
  },
  {
    "id": "5",
    "title": "Thor: God of Thunder",
    "image": "https://i.imgur.com/5Z5Z5Z5.jpg",
    "price": 18.99,
    "url": "https://www.marvel.com/comics/issue/12349/thor_god_of_thunder",
    "character_name": "Thor",
    "category": "Superhero",
    "author": "Jason Aaron",
    "publish_year": 2013
  },
  {
    "id": "6",
    "title": "Deadpool: The Complete Collection",
    "image": "https://i.imgur.com/6Z6Z6Z6.jpg",
    "price": 29.99,
    "url": "https://www.marvel.com/comics/issue/12350/deadpool_the_complete_collection",
    "character_name": "Deadpool",
    "category": "Superhero",
    "author": "Gerry Duggan",
    "publish_year": 2015
  },
  {
    "id": "7",
    "title": "Captain America: Winter Soldier",
    "image": "https://i.imgur.com/7Z7Z7Z7.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12351/captain_america_winter_soldier",
    "character_name": "Captain America",
    "category": "Superhero",
    "author": "Ed Brubaker",
    "publish_year": 2004
  },
  {
    "id": "8",
    "title": "Iron Man: Extremis",
    "image": "https://i.imgur.com/8Z8Z8Z8.jpg",
    "price": 17.99,
    "url": "https://www.marvel.com/comics/issue/12352/iron_man_extremis",
    "character_name": "Iron Man",
    "category": "Superhero",
    "author": "Warren Ellis",
    "publish_year": 2005
  },
  {
    "id": "9",
    "title": "Hawkeye: My Life as a Weapon",
    "image": "https://i.imgur.com/9Z9Z9Z9.jpg",
    "price": 16.99,
    "url": "https://www.marvel.com/comics/issue/123 ",
    "character_name": "Hawkeye",
    "category": "Superhero",
    "author": "Matt Fraction",
    "publish_year": 2012
  },
  {
    "id": "10",
    "title": "Doctor Strange: The Way of the Weird",
    "image": "https://i.imgur.com/10Z10Z10.jpg",
    "price": 21.99,
    "url": "https://www.marvel.com/comics/issue/12354/doctor_strange_the_way_of_the_weird",
    "character_name": "Doctor Strange",
    "category": "Superhero",
    "author": "Jason Aaron",
    "publish_year": 2015
  },
  {
    "id": "11",
    "title": "The Amazing Spider-Man: The Night Gwen Stacy Died",
    "image": "https://i.imgur.com/11Z11Z11.jpg",
    "price": 14.99,
    "url": "https://www.marvel.com/comics/issue/12355/the_amazing_spider-man_the_night_gwen_stacy_died",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Gerry Conway",
    "publish_year": 1973
  },
  {
    "id": "12",
    "title": "The Incredible Hulk: Planet Hulk",
    "image": "https://i.imgur.com/12Z12Z12.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12356/the_incredible_hulk_planet_hulk",
    "character_name": "Hulk",
    "category": "Superhero",
    "author": "Greg Pak",
    "publish_year": 2006
  },
  {
    "id": "13",
    "title": "Fantastic Four: The Trial of Galactus",
    "image": "https://i.imgur.com/13Z13Z13.jpg",
    "price": 16.99,
    "url": "https://www.marvel.com/comics/issue/12357/fantastic_four_the_trial_of_galactus",
    "character_name": "Fantastic Four",
    "category": "Superhero",
    "author": "John Byrne",
    "publish_year": 1982
  },
  {
    "id": "14",
    "title": "Guardians of the Galaxy: Cosmic Avengers",
    "image": "https://i.imgur.com/14Z14Z14.jpg",
    "price": 22.99,
    "url": "https://www.marvel.com/comics/issue/12358/guardians_of_the_galaxy_cosmic_avengers",
    "character_name": "Guardians of the Galaxy",
    "category": "Superhero",
    "author": "Brian Michael Bendis",
    "publish_year": 2014
  },
  {
    "id": "15",
    "title": "The Mighty Thor: The God Butcher",
    "image": "https://i.imgur.com/15Z15Z15.jpg",
    "price": 18.99,
    "url": "https://www.marvel.com/comics/issue/12359/the_mighty_thor_the_god_butcher",
    "character_name": "Thor",
    "category": "Superhero",
    "author": "Jason Aaron",
    "publish_year": 2013
  },
  {
    "id": "16",
    "title": "Wolverine: Old Man Logan",
    "image": "https://i.imgur.com/16Z16Z16.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12360/wolverine_old_man_logan",
    "character_name": "Wolverine",
    "category": "Superhero",
    "author": "Mark Millar",
    "publish_year": 2008
  },
  {
    "id": "17",
    "title": "Moon Knight: The Bottom",
    "image": "https://i.imgur.com/17Z17Z17.jpg",
    "price": 15.99,
    "url": "https://www.marvel.com/comics/issue/12361/moon_knight_the_bottom",
    "character_name": "Moon Knight",
    "category": "Superhero",
    "author": "Doug Moench",
    "publish_year": 2006
  },
  {
    "id": "18",
    "title": "The Punisher: Welcome Back, Frank",
    "image": "https://i.imgur.com/18 Z18.jpg",
    "price": 24.99,
    "url": "https://www.marvel.com/comics/issue/12362/the_punisher_welcome_back_frank",
    "character_name": "The Punisher",
    "category": "Superhero",
    "author": "Garth Ennis",
    "publish_year": 2000
  },
  {
    "id": "19",
    "title": "Daredevil: Born Again",
    "image": "https://i.imgur.com/19Z19Z19.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12363/daredevil_born_again",
    "character_name": "Daredevil",
    "category": "Superhero",
    "author": "Frank Miller",
    "publish_year": 1986
  },
  {
    "id": "20",
    "title": "Black Widow: The Finely Woven Thread",
    "image": "https://i.imgur.com/20Z20Z20.jpg",
    "price": 21.99,
    "url": "https://www.marvel.com/comics/issue/12364/black_widow_the_finely_woven_thread",
    "character_name": "Black Widow",
    "category": "Superhero",
    "author": "Nathan Edmondson",
    "publish_year": 2014
  },
  {
    "id": "21",
    "title": "Captain Marvel: Higher, Further, Faster, More",
    "image": "https://i.imgur.com/21Z21Z21.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12365/captain_marvel_higher_further_faster_more",
    "character_name": "Captain Marvel",
    "category": "Superhero",
    "author": "Kelly Sue DeConnick",
    "publish_year": 2014
  },
  {
    "id": "22",
    "title": "She-Hulk: Single Green Female",
    "image": "https://i.imgur.com/22Z22Z22.jpg",
    "price": 16.99,
    "url": "https://www.marvel.com/comics/issue/12366/she-hulk_single_green_female",
    "character_name": "She-Hulk",
    "category": "Superhero",
    "author": "Dan Slott",
    "publish_year": 2005
  },
  {
    "id": "23",
    "title": "The Vision: Little Worse Than a Man",
    "image": "https://i.imgur.com/23Z23Z23.jpg",
    "price": 17.99,
    "url": "https://www.marvel.com/comics/issue/12367/the_vision_little_worse_than_a_man",
    "character_name": "Vision",
    "category": "Superhero",
    "author": "Tom King",
    "publish_year": 2015
  },
  {
    "id": "24",
    "title": "Spider-Gwen: Greater Power",
    "image": "https://i.imgur.com/24Z24Z24.jpg",
    "price": 16.99,
    "url": "https://www.marvel.com/comics/issue/12368/spider-gwen_greater_power",
    "character_name": "Spider-Gwen",
    "category": "Superhero",
    "author": "Jason Latour",
    "publish_year": 2015
  },
  {
    "id": "25",
    "title": "The Amazing Spider-Man: Renew Your Vows",
    "image": "https://i.imgur.com/25Z25Z25.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12369/the_amazing_spider-man_renew_your_vows",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Gerry Conway",
    "publish_year": 2015
  },
  {
    "id": "26",
    "title": "The Ultimates: Omniversal",
    "image": "https://i.imgur.com/26Z26Z26.jpg",
    "price": 24.99,
    "url": "https://www.marvel.com/comics/issue/12370/the_ultimates_omniversal",
    "character_name": "The Ultimates",
    "category": "Superhero",
    "author": "Al Ewing",
    "publish_year": 201 
  },
  {
    "id": "27",
    "title": "Black Panther: The Intergalactic Empire of Wakanda",
    "image": "https://i.imgur.com/27Z27Z27.jpg",
    "price": 22.99,
    "url": "https://www.marvel.com/comics/issue/12371/black_panther_the_intergalactic_empire_of_wakanda",
    "character_name": "Black Panther",
    "category": "Superhero",
    "author": "Ta-Nehisi Coates",
    "publish_year": 2018
  },
  {
    "id": "28",
    "title": "Thor: The Worthy",
    "image": "https://i.imgur.com/28Z28Z28.jpg",
    "price": 18.99,
    "url": "https://www.marvel.com/comics/issue/12372/thor_the_worthy",
    "character_name": "Thor",
    "category": "Superhero",
    "author": "Jason Aaron",
    "publish_year": 2015
  },
  {
    "id": "29",
    "title": "The Mighty Thor: The Death of Mighty Thor",
    "image": "https://i.imgur.com/29Z29Z29.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12373/the_mighty_thor_the_death_of_mighty_thor",
    "character_name": "Thor",
    "category": "Superhero",
    "author": "Jason Aaron",
    "publish_year": 2017
  },
  {
    "id": "30",
    "title": "X-Men: Red",
    "image": "https://i.imgur.com/30Z30Z30.jpg",
    "price": 16.99,
    "url": "https://www.marvel.com/comics/issue/12374/x-men_red",
    "character_name": "X-Men",
    "category": "Superhero",
    "author": "Tom Taylor",
    "publish_year": 2018
  },
  {
    "id": "31",
    "title": "Fantastic Four: The New Fantastic Four",
    "image": "https://i.imgur.com/31Z31Z31.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12375/fantastic_four_the_new_fantastic_four",
    "character_name": "Fantastic Four",
    "category": "Superhero",
    "author": "Peter David",
    "publish_year": 1990
  },
  {
    "id": "32",
    "title": "The Amazing Spider-Man: The Clone Saga",
    "image": "https://i.imgur.com/32Z32Z32.jpg",
    "price": 24.99,
    "url": "https://www.marvel.com/comics/issue/12376/the_amazing_spider-man_the_clone_saga",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Various",
    "publish_year": 1996
  },
  {
    "id": "33",
    "title": "The Avengers: The Kree-Skrull War",
    "image": "https://i.imgur.com/33Z33Z33.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12377/the_avengers_the_kree-skrull_war",
    "character_name": "Avengers",
    "category": "Superhero",
    "author": "Roy Thomas",
    "publish_year": 1971
  },
  {
    "id": "34",
    "title": "The Invincible Iron Man: The Five Nightmares",
    "image": "https://i.imgur.com/34Z34Z34.jpg",
    "price": 22.99,
    "url": "https://www.marvel.com/comics/issue/12378/the_invincible_iron_man_the_five_nightmares",
    "character_name": "Iron Man",
    "category": "Superhero",
    "author": "Matt Fraction",
    "publish_year": 2008
  },
  {
    "id": "35",
    "title": "The Mighty Thor: The God of Thunder",
    "image": "https://i.imgur.com/35Z35Z35.jpg",
    "price": 18.99,
    "url": "https://www.marvel.com/comics/issue/12379/the_mighty_thor_the_god_of_thunder",
    "character_name": "Thor",
    "category": "Superhero",
    "author": "Jason Aaron",
    "publish_year": 2012
  },
  {
    "id": "36",
    "title": "The Amazing Spider-Man: The Gauntlet",
    "image": "https://i.imgur.com/36Z36Z36.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12380/the_amazing_spider-man_the_gauntlet",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Various",
    "publish_year": 2010
  },
  {
    "id": "37",
    "title": "The Ultimates: The New Ultimates",
    "image": "https://i.imgur.com/37Z37Z37.jpg",
    "price": 22.99,
    "url": "https://www.marvel.com/comics/issue/12381/the_ultimates_the_new_ultimates",
    "character_name": "The Ultimates",
    "category": "Superhero",
    "author": "Jeph Loeb",
    "publish_year": 2010
  },
  {
    "id": "38",
    "title": "The Amazing Spider-Man: Spider-Verse",
    "image": "https://i.imgur.com/38Z38Z38.jpg",
    "price": 24.99,
    "url": "https://www.marvel.com/comics/issue/12382/the_amazing_spider-man_spider-verse",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Dan Slott",
    "publish_year": 2014
  },
  {
    "id": "39",
    "title": "The Avengers: The Infinity Gauntlet",
    "image": "https://i.imgur.com/39Z39Z39.jpg",
    "price": 19.99,
    "url": "https://www.marvel.com/comics/issue/12383/the_avengers_the_infinity_gauntlet",
    "character_name": "Avengers",
    "category": "Superhero",
    "author": "Jim Starlin",
    "publish_year": 1991
  },
  {
    "id": "40",
    "title": "The Amazing Spider-Man: The Death of Jean DeWolff",
    "image": "https://i.imgur.com/40Z40Z40.jpg",
    "price": 16.99,
    "url": "https://www.marvel.com/comics/issue/12384/the_amazing_spider-man_the_death_of_jean_dewolff",
    "character_name": "Spider-Man",
    "category": "Superhero",
    "author": "Peter David",
    "publish_year": 1985
  }
]
